version: "3.9"
# https://github.com/imixs/imixs-jsf-example/blob/master/docker-compose-openliberty.yml

services:

  liberty-batch-db:
    image: postgres:15
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - C:/tmp/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432

  liberty-batch-app:
    depends_on:
      - liberty-batch-db
    image: liberty-batch
    ports:
      - "9080:9080"
      - "9443:9443"

  nginx:
    depends_on:
      - liberty-batch-app
    image: nginx:latest
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
